### ISSUE TITLE
Support for STOMP protocol

### ISSUE THREAD

**Issue by binhudakhalid** [fmtn/a#183]

**Comment by northlander** [comment]
Need a JMS compliant library for STOMP to implement this, since A is built around JMS. The [only library I can find](https://github.com/fusesource/stompjms) is outdated with last commit 8 years ago.

**Comment by erwindon** [comment]
should @binhudakhalid be able to use that library, just by using the `--jndi` and `--jndi-cf-name org.fusesource.stomp.jms.StompJmsConnectionFactory` options from `a`?
(with that jar in the classpath of course)

btw.: I saw a few commits in `stompjms` from 2 contributors that are also involved in the development of ActiveMQ Artemis.

**Comment by northlander** [comment]
Yes, in theory it should be possible to use the jndi configuration. I tried it out with IBM (WebSphere) MQ once upon a time and it worked just fine. Great idea, I think that will be the conclusion of this issue since it's a bad idea to bundle outdated libs and too many of them since the bundle size increases.

The stompjms project is (was?) from FuseSource, a company that was heavily involved in Apache Camel/ActiveMQ/ServiceMix back in the days before they were aquired by RedHat. So I guess this JMS library is essentially written to support the STOMP protocol in ActiveMQ. Not really supprising to see people still with RedHat working in the same domain.
